# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Clean Install
        run: npm ci

      - name: Test
        run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Update npm
        run: npm install -g npm@latest
      - name: Clean Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Setup Files
        run: |
          cp -r *.md ./dist/ && \
          cp package.json ./dist/package.json && \
          cd ./dist && rm *.test.*
      - name: Publish
        run: npm publish ./dist --access public
